id: I47A1E1E7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T16:01:57+00:00'
last_modified: '2022-06-10T04:03:04.478633+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30124
  title: བདེ་མཆོག་མཁའ་འགྲོ་སྙན་རྒྱུད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7E24:
      image_group_id: I5884
      title: ''
      total_pages: 984
      order: 1
      base_file: 7E24.txt
    D9CE:
      image_group_id: I5885
      title: ''
      total_pages: 824
      order: 2
      base_file: D9CE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
