id: P000316
initial_creation_type: ocr
created_at: 12/03/2020
last_modified_at: 2021-12-16 15:33:39.263686
source_metadata:
  id: bdr:W30124
  title: བདེ་མཆོག་མཁའ་འགྲོ་སྙན་རྒྱུད།
  author: ''
  volumes:
    9964a324d1be4cf1a6cb3de4b2c3a2fa:
      image_group_id: I5884
      title: ''
      volume_number: 1
      total_pages: 984
      base_file: v001.txt
    cfdf93f658f64f5992fd79755aa18daf:
      image_group_id: I5885
      title: ''
      volume_number: 2
      total_pages: 824
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
